name: local_storage_category_api
description: A Flutter implementation of the category API that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  category_api:
    path: ../category_api
  flutter:
    sdk: flutter
  meta: ^1.9.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
